from django.urls import path
from . import views
urlpatterns = [
 path('', views.index, name= "books.index"),
 path('list_books/', views.list_books, name= "books.list_books"),
 path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
 path('aboutus/', views.aboutus, name="books.aboutus"),
 path('html5/links/', views.html5_links, name='html5_links'),
 path('html5/text/formatting', views.text_formatting, name='text_formatting'),
 path('html5/listing',views.listing, name="listing"),
 path('html5/tables', views.html5_tables, name='html5_tables'),
 path('search', views.Search, name='Search'),
 path('simple/query', views.simple_query, name='simple_query'),
 path('complex/query', views.complex_query, name='complex_query'),
  path('lab8/task1', views.task1, name='task1'),
  path('lab8/task2', views.task2, name='task2'),
  path('lab8/task3', views.task3, name='task3'),
  path('lab8/task4', views.task4, name='task4'),
  path('lab8/task5', views.task5, name='task5'),
path('lab8/task6', views.task6, name='task6'),
path('lab10_part1/listbooks', views.listbooks, name='listbooks'),
path('lab10_part1/editbook/<int:bookId>', views.editbook, name='editbook'),
path('lab10_part1/deletebook/<int:bookId>', views.deletebook, name='deletebook'),
path('lab10_part1/addbook', views.addbook, name='addbook'),
path('lab10_part2/listbooks', views.listbooks2, name='listbooks2'),
path('lab10_part2/editbook/<int:bookId>', views.editbook2, name='editbook2'),
path('lab10_part2/deletebook/<int:bookId>', views.deletebook2, name='deletebook2'),
path('lab10_part2/addbook', views.addbook2, name='addbook2'),

path('lab9/task1', views.lab9task1, name='lab9task1'),
path('lab9/task2', views.lab9task2, name='lab9task2'),
path('lab9/task3', views.lab9task3, name='lab9task3'),
path('lab9/task4', views.lab9task4, name='lab9task4'),
]

